import { Container, Header } from "@/shared/components/shared";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza | Заказ",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Container>
        <Header
          hasSearch={false /*7a*/}
          hasCart={false /*7b*/}
          className="border-gray-200" /*5a*/
        />
        {children}
      </Container>
    </main>
  );
} /*3a*/

// 3b. Create checkout folder in (checkout)
// 3c(end). Create and go to page.tsx in checkout folder of (checkout) folder
// 5b(end). Go to header.tsx component
// 7c(end). Go to page.tsx of checkout folder
